### ISSUE TITLE
Chisel seems to hang reducing bzip

### ISSUE THREAD

**Issue by michaelbrownuc** [aspire-project/ChiselBench#3]
When reducing bzip, chisel seems to hang when reducing mySIGSEGVorSIGBBUScatcher.

I've tried on two different machines, the second with more than enough hardware horsepower.  In both cases I let chisel run in excess of 18 hours.

I can manually kill the process and use the results, but I'm guessing this leaves a significant portion of the code unreduced.

**Comment by KihongHeo** [comment]
Thanks for reporting that.
Since we have recently updated the test script a lot and have been always using Chisel on our machine, some unknown behavior might happen in another machine. Chisel is deterministic, the current benchmarks (unix utilities) are presumably deterministic, but only timeout can cause different results.

Here I guess the problem may be because the reduced program blocks timeout signal `SIGTERM`. So can you try to change `export TIMEOUT=1` to `export TIMEOUT="-k 1 1"` in  test.sh`?

**Comment by michaelbrownuc** [comment]
Changing the timeout as you suggested fixes the problem.  Both gzip and Bzip terminate and produce expected results.  Thanks!
